networks:
  default:
    attachable: true
    name: neko-rooms

services:
  traefik:
    image: traefik:2.4
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    command:
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms"
      - "--entrypoints.web.address=:8080"
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./usersfile:/usersfile:ro

  neko-rooms:
    image: m1k1o/neko-rooms:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      NEKO_ROOMS_EPR: 52000-52100
      #NEKO_ROOMS_NAT1TO1: 192.168.x.x #IP of server to access locally
      NEKO_ROOMS_TRAEFIK_ENTRYPOINT: web
      NEKO_ROOMS_TRAEFIK_NETWORK: neko-rooms
      NEKO_ROOMS_INSTANCE_URL: https://neko.yourdomain.tld/
      NEKO_ROOMS_PATH_PREFIX: /room/
      NEKO_ROOMS_NEKO_IMAGES: ghcr.io/m1k1o/neko/firefox:latest ghcr.io/m1k1o/neko/intel-firefox:latest ghcr.io/m1k1o/neko/intel-chromium:latest ghcr.io/m1k1o/neko/intel-google-chrome:latest ghcr.io/m1k1o/neko/intel-microsoft-edge:latest
      NEKO_ROOMS_STORAGE_ENABLED: true
      NEKO_ROOMS_STORAGE_INTERNAL: /data
      NEKO_ROOMS_STORAGE_EXTERNAL: /root/neko-rooms/data
      NEKO_ROOMS_DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    labels:
      traefik.enable: true
      traefik.http.services.neko-rooms-frontend.loadbalancer.server.port: 8080
      traefik.http.routers.neko-rooms.entrypoints: web
      traefik.http.routers.neko-rooms.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.neko-rooms.priority: 1
      traefik.http.middlewares.nrooms-auth.basicauth.usersfile: /usersfile
      traefik.http.routers.neko-rooms.middlewares: nrooms-auth

  rtsp_server:
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: unless-stopped
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      #- "8889:8889" # WebRTC
      #- "8890:8890" # SRT
    environment:
      MTX_PROTOCOLS: tcp
      #MTX_WEBRTCADDITIONALHOSTS: mtx.yourdomain.tld # most likely not needed
      MTX_HLSALWAYSREMUX: yes # constantly remuxes stream regardless if anyone watching or not
      MTX_HLSVARIANT: mpegts #mpegts fmp4 or lowLatency
      MTX_HLSSEGMENTCOUNT: 7
      MTX_HLSSEGMENTDURATION: 2s
      MTX_PATHS_LIVE_SOURCE: "udp://rtsp_server:1234" # Configure multiple MTX_PATHS_ if you want to broadcast on multiple rooms concurrently
      MTX_PATHS_PARTY_SOURCE: "udp://rtsp_server:1235"
      MTX_PATHS_MOVIE_SOURCE: "udp://rtsp_server:1236"
